### ISSUE TITLE
能否添加目标检测支持

### ISSUE THREAD

**Issue by mingtianquan** [FeilongTest/go-ddddocr#2]
能否添加目标检测支持

**Comment by mingtianquan** [comment]
![QQ截图20240528032949](https://github.com/FeilongTest/go-ddddocr/assets/157282579/b69d8bcd-5dd4-46c0-a266-29f412f1d412)

**Comment by mingtianquan** [comment]
目前这版本也运行不起来报错3个地方

**Comment by mingtianquan** [comment]
![Uploading QQ截图20240603133829.png…]()

**Comment by mingtianquan** [comment]
![QQ截图20240603133829](https://github.com/FeilongTest/go-ddddocr/assets/157282579/9ce16e8a-a15e-4db4-912c-486fa6195f3d)

**Comment by mingtianquan** [comment]
请教下  无法正常输出结果  这是怎么回事呢。。。

**Comment by FeilongTest** [comment]
> 能否添加目标检测支持
![微信截图_20240603164106](https://github.com/FeilongTest/go-ddddocr/assets/29750819/7578e601-45f5-49d4-85a1-065d950e56a5)


> 请教下 无法正常输出结果 这是怎么回事呢。。。

使用gocv可以实现目标检测，之前写过的代码找不到了，暂时不会加入目标检测

可能是你的模型文件使用出错了，可以使用绝对路径的原ddddocr中的onnx模型试试，路径大致为：C:\\Users\\用户名\\AppData\\Local\\Programs\\Python\\Python版本\\lib\\site-packages\\ddddocr\\common.onnx

**Comment by mingtianquan** [comment]
大佬  是使用的绝对路径呀，路径没错。  就是报错不自动啥原因，。

**Comment by FeilongTest** [comment]
需要使用2024-1月之前的common.onnx模型,因原仓库后续模型更新,会出现你出现的问题，我会将我使用的模型文件提交到仓库
